// App Store genre IDs (legacy iTunes RSS feed) -> internal AppCategory.
// IDs match Apple's published genre catalog; keep in sync if Apple
// adds new top-level genres (rare).

export const GENRES = [
  { id: 6000, name: 'Business' },
  { id: 6001, name: 'Weather' },
  { id: 6002, name: 'Utilities' },
  { id: 6003, name: 'Travel' },
  { id: 6004, name: 'Sports' },
  { id: 6005, name: 'Social Networking' },
  { id: 6006, name: 'Reference' },
  { id: 6007, name: 'Productivity' },
  { id: 6008, name: 'Photo & Video' },
  { id: 6009, name: 'News' },
  { id: 6010, name: 'Navigation' },
  { id: 6011, name: 'Music' },
  { id: 6012, name: 'Lifestyle' },
  { id: 6013, name: 'Health & Fitness' },
  { id: 6014, name: 'Games' },
  { id: 6015, name: 'Finance' },
  { id: 6016, name: 'Entertainment' },
  { id: 6017, name: 'Education' },
  { id: 6018, name: 'Books' },
  { id: 6020, name: 'Medical' },
  { id: 6021, name: 'Magazines & Newspapers' },
  { id: 6022, name: 'Catalogs' },
  { id: 6023, name: 'Food & Drink' },
  { id: 6024, name: 'Shopping' },
  { id: 6026, name: 'Developer Tools' },
  { id: 6027, name: 'Graphics & Design' },
];

// Maps Apple's primaryGenreName (from /lookup) to our internal AppCategory.
// Falls back to 'other' for anything unmapped.
export const GENRE_TO_CATEGORY = {
  'Books': 'education',
  'Business': 'productivity',
  'Catalogs': 'shopping',
  'Developer Tools': 'developer',
  'Education': 'education',
  'Entertainment': 'entertainment',
  'Finance': 'finance',
  'Food & Drink': 'food',
  'Games': 'entertainment',
  'Graphics & Design': 'utilities',
  'Health & Fitness': 'health',
  'Lifestyle': 'other',
  'Magazines & Newspapers': 'news',
  'Medical': 'health',
  'Music': 'music',
  'Navigation': 'travel',
  'News': 'news',
  'Photo & Video': 'entertainment',
  'Productivity': 'productivity',
  'Reference': 'education',
  'Shopping': 'shopping',
  'Social Networking': 'social',
  'Sports': 'entertainment',
  'Stickers': 'other',
  'Travel': 'travel',
  'Utilities': 'utilities',
  'Weather': 'utilities',
};
