//
//  AppDatabaseLoader.swift
//  Fore
//
//  Loads the bundled AppDatabase.json — the App Store-derived corpus
//  the picker draws from. Decodes raw entries, resolves install status
//  via canOpenURL, and exposes a couple of helpers for tri-state UI.
//
//  The JSON is generated by tools/crawler/crawl.js. Schema:
//    id            String   bundle ID (preferred) or "legacy:..." fallback
//    trackId       Int?     numeric App Store ID
//    name          String   user-facing name
//    developer     String?
//    primaryGenre  String?  App Store genre (display only)
//    category      String   internal AppCategory raw value
//    iconURL       String?  https artwork URL (256×256)
//    urlScheme     String?  nullable — apps without a known scheme route
//                           the user into the Custom App sheet
//    schemeSource  String?  "official" | "community" | nil
//    verifiedAt    String?  ISO date, advisory only
//

import Foundation
import UIKit

struct AppDatabaseEntry: Codable, Hashable, Identifiable {
    var id: String
    var trackId: Int?
    var name: String
    var developer: String?
    var primaryGenre: String?
    var category: AppCategory
    var iconURL: String?
    var urlScheme: String?
    var schemeSource: String?
    var verifiedAt: String?

    /// True when the database has a known launch scheme for this app.
    /// Picker rows without a scheme are visually distinct and route to
    /// the Custom App sheet instead of the bulk-add commit path.
    var hasScheme: Bool { urlScheme?.isEmpty == false }
}

enum AppDatabaseLoaderError: Error {
    case fileNotFound
    case decodingFailed(Error)
}

struct AppDatabaseLoader {
    static let bundledFileName = "AppDatabase"
    static let bundledFileExtension = "json"

    static func loadBundledEntries(bundle: Bundle = .main) throws -> [AppDatabaseEntry] {
        guard let url = bundle.url(forResource: bundledFileName, withExtension: bundledFileExtension) else {
            throw AppDatabaseLoaderError.fileNotFound
        }
        let data = try Data(contentsOf: url)
        do {
            return try JSONDecoder().decode([AppDatabaseEntry].self, from: data)
        } catch {
            throw AppDatabaseLoaderError.decodingFailed(error)
        }
    }

    /// Tri-state install status. iOS only lets `canOpenURL` verify schemes
    /// listed in `LSApplicationQueriesSchemes` (cap of 50) plus Apple
    /// system schemes. For schemes outside that set we genuinely don't
    /// know — callers decide what to do with `unverified`.
    enum InstallStatus {
        case installed       // canOpenURL returned true
        case notInstalled    // declared scheme, canOpenURL returned false
        case unverified      // scheme not declared; iOS won't tell us
        case noScheme        // entry has no urlScheme at all
    }

    /// Resolves install status for each entry. Must run on the main actor.
    @MainActor
    static func resolveInstalled(_ entries: [AppDatabaseEntry]) -> [(entry: AppDatabaseEntry, status: InstallStatus)] {
        let declared = declaredQueriesSchemes()
        return entries.map { entry in
            (entry, status(for: entry.urlScheme, declared: declared))
        }
    }

    /// Optimistic boolean for AppEntry.isInstalled at write time:
    /// treat `unverified` as installed so home-screen icons stay
    /// at full opacity for things we genuinely can't verify.
    @MainActor
    static func optimisticIsInstalled(scheme: String?) -> Bool {
        switch status(for: scheme, declared: declaredQueriesSchemes()) {
        case .installed, .unverified: return true
        case .notInstalled, .noScheme: return false
        }
    }

    @MainActor
    private static func status(for urlScheme: String?, declared: Set<String>) -> InstallStatus {
        guard let urlScheme, !urlScheme.isEmpty else { return .noScheme }
        guard let url = URL(string: urlScheme),
              let scheme = url.scheme?.lowercased() else {
            return .notInstalled
        }
        if UIApplication.shared.canOpenURL(url) { return .installed }
        return declared.contains(scheme) ? .notInstalled : .unverified
    }

    private static func declaredQueriesSchemes() -> Set<String> {
        let raw = Bundle.main.object(forInfoDictionaryKey: "LSApplicationQueriesSchemes") as? [String] ?? []
        return Set(raw.map { $0.lowercased() })
    }
}
